### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by karuban88** [cameronhimself/vue-drag-drop#17]
The component works fine with Google Chrome, Safari and Firefox but on IE11 it doesn't.

I have this error on drag start:
SCRIPT65535: Unexpected call to method or property access.

Then when I over Dropzone I have:
SCRIPT438: Object doesn't support property or method 'find'

**Comment by cameronhimself** [comment]
So, I solved that specific error you reported, but that brought to light another error, and t looks like, unfortunately, it's not going to be possible to support any version of IE. To send data between a draggable item and a dropzone requires calling [`setData(format, data)`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData) on the [`dataTransfer`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) object. There's an IE-specific issue with the `format` argument for `setData`: it has to be precisely `'text'`, whereas the spec allows it to be any mimetype (really any string at all).

Why is that a problem? Because this component abuses the `format` argument to support having `transferData` available in all events. It sets it to a globally unique identifier, and uses that as a key in a persistent data store--that's how it pulls data for every event, despite the spec only allowing it for `drop`.

I don't see any way around this and I'm really sorry :disappointed:  It's a trade-off between making the API more usable and supporting older browsers, and I don't want to compromise on the API, especially since people are relying on it.

**Comment by cameronhimself** [comment]
1.0.0 has been released with IE/Edge support.
