### ISSUE TITLE
Nested <drag> components

### ISSUE THREAD

**Issue by eidellev** [cameronhimself/vue-drag-drop#20]
Hi,
First of all - thanks for this library. It fits my current project like a glove :-)

There seems to be an issue with nesting `<drag>` components. The child's `trasfer-data` gets overwritten by the parent (in my case, I am trying to drag items between lists that are themselves draggable). 

package versions:
"nuxt": "1.3.0", (vue 2.5.13)
"vue-drag-drop": "0.2.3"

Thanks!

**Comment by cameronhimself** [comment]
Thanks, I'll take a look. If there's any way you could put together a JSFiddle demonstrating the problem  that would be an enormous help.

**Comment by cameronhimself** [comment]
Nevermind, I'm too quick for ya :zap: 

I'm going to ponder a more elegant way to do this, but for now here's a quick fix. You have to `stopPropagation` on the child's native event:

```vue
<template>
  ...
  <drag :transferData="{ position: 'parent' }">
    <drag @dragstart="handleChildDragstart" :transferData="{ position: 'child' }">child</drag>
  </drag>
  ...
</template>

<script>
  export default {
    methods: {
      handleChildDragstart(data, event) {
        event.stopPropagation();
      }
    }
  };
</script>
```

Let me know if this works for you.

**Comment by eidellev** [comment]
Awesome! That did the trick 👍

**Comment by cameronhimself** [comment]
Having thought about this scenario, I don't think there's an elegant way to handle it. Due to the isolated nature of components, I don't think there's a way one drag component to know it's inside another without something really messy like querying the DOM (and I'm not even sure how that would work). So for now I'm resolving this with documentation, by adding an example to the [demo page](https://cameronhimself.github.io/vue-drag-drop/).

Thanks for the report!
