### ISSUE TITLE
slot for icons 

### ISSUE THREAD

**Issue by haexhub** [cameronhimself/vue-drag-drop#24]
hi,

could you please add the posibility, to use icons instead of image slot, like material design icons?
https://materialdesignicons.com/

**Comment by cameronhimself** [comment]
This can already be done using the [image slot](https://github.com/cameronhimself/vue-drag-drop#image-1) (browser support is spotty, though, due to the underlying browser API, not this package). I don't wish to add special syntax for any particular icon set, since it goes against the goals of this package.
