### ISSUE TITLE
Firefox issue (with example)

### ISSUE THREAD

**Issue by liquidvisual** [cameronhimself/vue-drag-drop#47]
I'm not sure why, but I can't seem to get this working in Firefox. It tries to launch a new window and leave the page. Does anyone know what I could try?

https://codepen.io/liquidvisual/pen/zjgVzz?editors=1011 (open in Firefox)

**Comment by cameronhimself** [comment]
So, this is extremely strange, but the issue seems to be that you're only doing `console.log` inside your drop handler. If you do an `alert` rather than `console.log` the problem goes away. I have no idea why this is the case. I've found that Firefox seems to have a lot of idiosyncrasies when it comes to the Drag and Drop API.

**Comment by liquidvisual** [comment]
Thanks for taking a look. Is there anything else I can use beside 'alert' that will work? I've tried changing data, setting timeouts and various other actions but outside of any alert it'll send the page elsewhere.

In my real application, I'm committing actions with Vuex - and getting this unwanted behaviour. Cheers!

**Comment by cameronhimself** [comment]
Whaaaat, you mean you don't issue an `alert` in every event handler like a real alpha developer? 🤔 

Seriously though, it looks you can resolve this by using `event.preventDefault` in the drop handler. I've forked your JSBin [here](https://codepen.io/anon/pen/JZPxGP?editors=1011). Reopening since this is clearly an issue that should be resolved by this lib. Thanks for bringing it to my attention.

**Comment by cameronhimself** [comment]
I updated the [JSBin ](https://codepen.io/anon/pen/JZPxGP?editors=1011) to function more like what it looks like you're going for (having both the drag and drop data in the event handler). I think your use of `$event` isn't right.

**Comment by liquidvisual** [comment]
haha, in retrospect the alert thing did sound pretty stupid. Duly noted! 

Thanks so much for that, the pen works great and Firefox is happy. Awesome.

**Comment by cameronhimself** [comment]
Any and all stupidity was on my end. Thanks for being persistent.

**Comment by cameronhimself** [comment]
Resolved by 5df97fe460d4cdd45090a0eb2e823e19cf17bcc3, new version published to NPM (1.1.0 because it technically changes the API).
