### ISSUE TITLE
How do we make the drag "look/style" be exactly the same as the item we are dragging?

### ISSUE THREAD

**Issue by dfarrNTST** [cameronhimself/vue-drag-drop#58]
We need the dragging look and feel to appear exactly the same as the item we clicked on to drag.  Out of the box, it appears to be setting heavy transparency and we can hardly see anything.  How can we make the draggable look be identical to what we clicked on to drag?

**Comment by Pavel-Son** [comment]
I also think, that saving mouse position relative to dragging item would be pretty cool. Current behavior is a bit different coz we kinda drag left-top corner every time

**Comment by cameronhimself** [comment]
This library is intended to be a very light-weight wrapper for easing the use of the native browser drag-and-drop functionality. What it specifically does not aim to do is _replace_ the browser functionality--it just makes it simpler and more consistent. Since the browser controls the rendering of the item during drag, changing it would require completely replacing the native browser functionality--explicitly against this library's purpose. So what you desire isn't achievable, at least not any time in the near future.

@StanleeLOD take a look at [this issue](https://github.com/cameronhimself/vue-drag-drop/issues/50)--particularly the fiddle link in my last comment. I think that will help you solve your problem.
