### ISSUE TITLE
changes in slot image does not seem to be reflected

### ISSUE THREAD

**Issue by MathieuDerelle** [cameronhimself/vue-drag-drop#61]
I'm updating the content of image slot on the event @dragstart but is does not show up.
The debug tool shows that the variables are updated. 

See this fiddle : 
https://jsfiddle.net/kc5ao03n/

The text appearing during dragging should be "dragging in progress".

Is there a workaround ?

**Comment by cameronhimself** [comment]
The issue is the timing of the `dragstart` event. Take a look at my comment [here](https://github.com/cameronhimself/vue-drag-drop/issues/50#issuecomment-396411125), which is a different problem, but results from the exact same timing issue. The solution here, as well, is to use a wrapping div with a `mousedown` event, at least for the time being--take a look at [this fiddle](https://jsfiddle.net/yp0hsv7n/). I might add a `mousedown` event to the `drag` element to alleviate these problems.
